image: timbru31/node-chrome:12

definitions:
    steps:
        - step: &test
              name: Latest Node N
              image: IMAGE
              caches:
                  - npm
              script:
                  - git submodule update --init
                  - scripts/common/npm/testCi.sh
    caches:
        npm12: ~/.npm
        npm14: ~/.npm
        npm16: ~/.npm
    branches:
        - branch: &fullTestAndTag
              - parallel:
                    - step:
                          <<: *test
                          name: Latest Node 12
                          image: timbru31/node-chrome:12
                          caches:
                              - npm12
                    - step:
                          <<: *test
                          name: Latest Node 14
                          image: timbru31/node-chrome:14
                          caches:
                              - npm14
                    -   step:
                            <<: *test
                            name: Latest Node 16
                            image: timbru31/node-chrome:16
                            caches:
                                - npm16
              - step:
                    name: Tag
                    caches:
                        - node
                    script:
                        - git submodule update --init
                        - scripts/common/git/tagBitbucket.sh

pipelines:
    branches:
        master: *fullTestAndTag
        feature/**: *fullTestAndTag
